sudo: false
language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

before_install:
  - ./setup-atlassian-sdk.sh `pwd`
  - export PATH=opt/atlassian-plugin-sdk/bin:opt/atlassian-plugin-sdk/apache-maven-*/bin:$PATH

install:
  - atlas-mvn install

script:
  - atlas-package

notifications:
  email: false

before_deploy:
  - export project_version=$(atlas-mvn help:evaluate -D -N -Dexpression=project.version | grep -v '\[')
  - echo $project_version
  - if [ $TRAVIS_BRANCH != "master" ]; then
      export branch_version=-$TRAVIS_BRANCH;
    fi
  - export deploy_version=$project_version$branch_version
  - echo "Deploy version - $deploy_version"
  - mv $TRAVIS_BUILD_DIR/target/prom-jira-exporter-$project_version.jar $TRAVIS_BUILD_DIR/target/prom-jira-exporter-$deploy_version.jar

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "target/prom-jira-exporter-$deploy_version.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: AndreyVMarkelov/jira-prometheus-exporter
  name: $deploy_version
